### ISSUE TITLE
Create a PNG logo

### ISSUE THREAD

**Issue by Dariusionut** [Dariusionut/user-management#28]
**We need a simple PNG logo for the application**

The name of the file must be logo.png
The png logo must be added in the resources/static/images/logo.png
Also add the file in the comment bellow to this ticket.

Good luck😊

**Comment by aureliosss** [comment]
![Image](https://user-images.githubusercontent.com/84960010/233793921-a499fdd9-169b-429f-aec2-174f8f801f49.png)

**Comment by Dariusionut** [comment]
It looks good, but I think we should adapt it to the application name in the future. For the moment we can use this

**Comment by gonciarstef** [comment]
![Image](https://user-images.githubusercontent.com/131298813/233797444-5cf580e8-c428-49a5-8390-2ec3a2031e0f.png)

How about this one?

**Comment by aureliosss** [comment]
It is a good alternative

**Comment by aureliosss** [comment]
![Image](https://user-images.githubusercontent.com/84960010/233797758-63c816a0-e01b-434c-aa63-8a7edcaea5fe.png)

**Comment by gabrielspiridon** [comment]
another version :)

![Image](https://user-images.githubusercontent.com/129274107/233956371-2b1a347f-9254-451c-8c77-b9a814bf1335.png)
