### ISSUE TITLE
Update user.html view

### ISSUE THREAD

**Issue by Dariusionut** [Dariusionut/user-management#29]
The user.html view must be updated and display the user details in a professional way. (don't display sensitive data such as passwords).

profile example

The user profile image section in the view can still be implemented and be be blank at the moment as we don't have it implemented yet, but we will do it in the future.

![Image](https://user-images.githubusercontent.com/44172060/233792995-1347980e-2779-4c19-827b-3870c892647d.jpeg)

**Comment by gonciarstef** [comment]
Does it have to be identical to the one in the picture? Or can we use a different style?
