### ISSUE TITLE
Study GIT - Stefania

### ISSUE THREAD

**Issue by Dariusionut** [Dariusionut/user-management#37]
[Amigoscode GIT course](https://amigoscode.com/courses/enrolled/1317178 )

[W3schools GIT tutorial](https://www.w3schools.com/git/default.asp?remote=github)

**Comment by gonciarstef** [comment]
:))

**Comment by gonciarstef** [comment]
1/2 Complete!

![Image](https://user-images.githubusercontent.com/131298813/233859839-f63ac199-fc99-41bd-9c4e-e605899d3e94.jpeg)

**Comment by gonciarstef** [comment]
![Image](https://user-images.githubusercontent.com/131298813/234008560-923fc0ae-4426-49c3-8f1d-7d39f23b873a.jpeg)
