### ISSUE TITLE
Study GIT - Cicero

### ISSUE THREAD

**Issue by Dariusionut** [Dariusionut/user-management#39]
[Amigoscode GIT course](https://amigoscode.com/courses/enrolled/1317178 )

[W3schools GIT tutorial](https://www.w3schools.com/git/default.asp?remote=github)

**Comment by CiceroNila** [comment]
Trebuie sa il trec in alta stare ?

**Comment by gonciarstef** [comment]
Da, muta-l in In progress daca te-ai apucat.

**Comment by Dariusionut** [comment]
- Analyzing : cand analizezi cerintele unui ticket
- In progress: cand ai inteles cerintele si te-ai apucat de treaba
- Study done: aici vor fi doar ticketele dedicate sudiilor care au fost finalizate

**Comment by Dariusionut** [comment]
De asemenea sa bifati si campul "start date" -> alegeti data in care v-ati apucat de acesta

**Comment by CiceroNila** [comment]
Ok, Multumesc

**Comment by Dariusionut** [comment]
Reminder: please try to finish this task
